window.MWPrint = (() => {
  const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
  const principles = () => `<table class="principles-table"><thead><tr><th>달러 시장 변화</th><th>원/달러 환율</th></tr></thead><tbody>${Object.values(MWData.causes).map(c => `<tr><td>${c.label}</td><td>${MWData.direction(c.rate)}</td></tr>`).join('')}</tbody></table>`;
  const pageHeading = (title, page) => `<header class="print-heading"><h1><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8h16m-4-4 4 4-4 4M20 16H4m4-4-4 4 4 4"/></svg>${title}</h1><span>${page} / 2</span></header>`;
  const identity = () => '<div class="print-identity"><span>이름 <i></i></span><span>모둠 <i></i></span><span>날짜 <i></i></span></div>';
  const worksheetGraphic = () => `<svg class="worksheet-graphic" viewBox="0 0 160 96" aria-hidden="true"><g fill="white" stroke="currentColor" stroke-width="2"><rect x="8" y="23" width="58" height="42" rx="7"/><rect x="92" y="37" width="58" height="42" rx="7"/></g><g fill="currentColor" text-anchor="middle" font-size="26" font-weight="650"><text x="37" y="53">₩</text><text x="121" y="67">$</text></g><g fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M48 12h69m-7-7 7 7-7 7M112 88H43m7-7-7 7 7 7"/></g></svg>`;
  const worksheetHeading = page => `<header class="worksheet-heading"><div class="worksheet-brand"><strong>머니워</strong><span>개인 기록지 · A4 1장 양면</span><span class="worksheet-page">${page === 1 ? '앞면' : '뒷면'} · ${page} / 2</span></div><div class="worksheet-title"><div><h1>${page === 1 ? '뉴스를 읽고, 환율의 이유를 밝혀라.' : '이번에는 혼자 설명하기'}</h1><p>${page === 1 ? '먼저 혼자 판단하고, 해설 뒤에 틀린 부분을 고쳐 보세요.' : '새로운 두 사례에 배운 내용을 적용해 보세요.'}</p></div>${worksheetGraphic()}</div></header>`;
  const choice = (a, b) => `<span class="circle-choice">[ <b>${a}</b> / <b>${b}</b> ]</span>`;
  const marketChoices = () => `<div class="worksheet-choice-sentences"><p>달러 ${choice('수요', '공급')}가<br>${choice('증가', '감소')}한다.</p><p>환율이 ${choice('상승', '하락')}한다.</p></div>`;
  const transactionChoices = () => `<p class="worksheet-transaction">달러를 ${choice('사는', '파는')} 거래가<br>${choice('늘어난다', '줄어든다')}.</p>`;
  function worksheet(length = 6) {
    return `<section class="print-sheet print-worksheet worksheet-rounds-${length}">${worksheetHeading(1)}${identity()}<div class="worksheet-reference"><p><strong>원/달러 환율</strong><span>1달러를 사는 데 필요한 원화 금액</span></p><p class="worksheet-direction">각 [ ] 안에서 알맞은 말 하나에 동그라미를 치세요.</p></div><table class="worksheet"><colgroup><col style="width:9%"><col style="width:42%"><col style="width:49%"></colgroup><thead><tr><th>라운드</th><th>최초 개인 판단<small>먼저 혼자 고르세요</small></th><th>해설 뒤 수정<small>틀렸다면 거래부터 다시 고르세요</small></th></tr></thead><tbody>${Array.from({ length }, (_, i) => `<tr><th scope="row">${String(i + 1).padStart(2, '0')}</th><td>${marketChoices()}</td><td>${transactionChoices()}${marketChoices()}</td></tr>`).join('')}</tbody></table></section><section class="print-sheet print-worksheet print-new-page worksheet-personal">${worksheetHeading(2)}${identity()}<p class="worksheet-circle-guide">각 [ ] 안에서 알맞은 말 하나에 동그라미를 치세요.</p>${MWData.individual.map((d, i) => `<article class="print-question"><h2><span>${String(i + 1).padStart(2, '0')}</span>${d.title}</h2><p>${d.text} 다른 조건은 같습니다.</p><div class="worksheet-personal-choices"><div><h3>① 거래 변화</h3>${transactionChoices()}</div><div><h3>② 원인과 환율</h3>${marketChoices()}</div></div><h3>뉴스에서 판단의 근거가 된 말에 밑줄을 그으세요.</h3></article>`).join('')}</section>`;
  }
  function summary(state) {
    return `<section class="print-sheet">${pageHeading('머니워 · 결과와 원리 정리', 1)}<p class="print-intro">${state.config.length}라운드 · 모둠별 ${state.config.length * MWCore.POINTS_PER_ROUND}점 만점 · 최초 제출 기준</p><h2>네 가지 관계</h2>${principles()}<h2>모둠 분석 결과</h2><table class="print-results"><thead><tr><th>순위</th><th>모둠</th><th>총점</th><th>수요·공급</th><th>증감</th><th>환율</th></tr></thead><tbody>${MWCore.ranking(state).map(r => `<tr><td>${r.tied ? '공동 ' : ''}${r.rank}위</td><th scope="row">${r.team + 1}. ${esc(r.name)}</th><td><strong>${r.total}/${state.config.length * MWCore.POINTS_PER_ROUND}</strong></td>${r.parts.map(p => `<td>${p}/${state.config.length}회</td>`).join('')}</tr>`).join('')}</tbody></table></section><section class="print-sheet print-new-page print-personal">${pageHeading('머니워 · 개인 확인 해설', 2)}${MWData.individual.map((d, i) => { const c = MWData.causes[d.cause]; return `<article class="print-question"><h2><span>${i + 1}</span>${d.title}</h2><p>${d.text}</p><dl class="print-explanation"><div><dt>거래 행동</dt><dd>${d.action}</dd></div><div><dt>달러 시장</dt><dd>${c.label}</dd></div><div><dt>환율</dt><dd>원/달러 환율 ${MWData.direction(c.rate)}</dd></div></dl></article>`; }).join('')}<p>개인 확인은 모둠 점수에 합치지 않습니다.</p><div class="print-template"><h2>새 뉴스에서도 달러 거래부터 설명해 보세요.</h2><p>뉴스의 거래 변화 → 달러를 사거나 파는 행동 → 수요·공급 변화 → 환율</p></div></section>`;
  }
  return { worksheet, summary, principles };
})();
