const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const C = require('../js/core.js');
const url = process.env.TEST_URL || 'http://127.0.0.1:8766';
const out = process.env.QA_OUTPUT_DIR || path.join(os.tmpdir(),'money-war-qa');
let browser;
(async () => {
  fs.mkdirSync(out,{recursive:true});
  browser = await chromium.launch({headless:true,...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {})});
  const context = await browser.newContext({viewport:{width:1280,height:720}});
  const page = await context.newPage(), errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const state = () => page.evaluate(key=>JSON.parse(localStorage.getItem(key)),C.STORAGE_KEY);
  const phase = () => page.locator('#app').getAttribute('data-phase');
  const settled = () => page.waitForFunction(()=>!document.querySelector('#app').hasAttribute('aria-busy'));
  const key = async value => {await page.keyboard.press(value);await settled();};
  await page.goto(url);
  await page.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key:C.STORAGE_KEY,s:C.create({count:2,length:4})});
  await page.reload(); await page.locator('[data-action="resume"]').click();
  await key('n'); assert.equal(await phase(),'newsReading','N advances the lesson');
  await page.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyN',key:'n',repeat:true,bubbles:true})));
  assert.equal(await phase(),'newsReading','holding a key does not skip stages');
  await key('t'); assert.equal((await state()).timer.deadline,null);
  const seconds=(await state()).timer.remaining; await key('+');
  assert.equal((await state()).timer.remaining,seconds+10);
  await key('t'); assert.ok((await state()).timer.deadline);
  await key('p'); assert.equal(await phase(),'rehearsal');
  await page.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyN',key:'ㅜ',bubbles:true})));
  await settled(); assert.equal(await phase(),'newsReading','physical keys work with Korean input selected');
  await page.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyN',key:'n',ctrlKey:true,bubbles:true})));
  assert.equal(await phase(),'newsReading','browser modifier shortcuts are preserved');
  await page.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyN',key:'n',isComposing:true,bubbles:true})));
  assert.equal(await phase(),'newsReading','IME composition is ignored');
  await key('h'); assert.equal(await page.locator('#dialog').evaluate(n=>n.open),true);
  assert.equal((await page.locator('#dialog').innerText()).includes('생활 적용'),false);
  await page.screenshot({path:path.join(out,'keyboard-help.png')});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'help fits the narrow screen');
  assert.ok(await page.locator('#dialog').evaluate(n=>n.scrollWidth<=n.clientWidth+1),'help has no clipped horizontal content');
  await page.screenshot({path:path.join(out,'keyboard-help-mobile.png'),fullPage:true});
  await key('n'); assert.equal(await phase(),'newsReading','dialog blocks lesson shortcuts');
  await page.locator('#shortcuts-enabled').uncheck(); await key('Escape');
  await page.setViewportSize({width:1280,height:720});
  await key('n'); assert.equal(await phase(),'newsReading','teacher can disable single-key shortcuts');
  await key('h'); assert.equal(await page.locator('#dialog').evaluate(n=>n.open),false);
  await page.locator('#menu').click(); await page.locator('[data-tool="shortcuts"]').click();
  await page.locator('#shortcuts-enabled').check(); await key('Escape');
  await page.locator('#menu').click(); await key('n'); assert.equal(await phase(),'newsReading','open menu blocks lesson shortcuts');
  await key('Escape'); await key('n'); await key('n'); await key('n');
  assert.equal(await phase(),'responseEntry');
  await key('n'); assert.equal(await phase(),'responseEntry','incomplete answers cannot be confirmed by keyboard');
  await key('v'); await key('n'); assert.equal(await phase(),'responseEntry'); await key('Escape');
  await key('1'); await key('5'); assert.equal((await state()).rounds[0].entries[0].cause,'A');
  const beforeMove=JSON.stringify((await state()).rounds[0].entries);
  await key('ArrowUp');
  assert.equal(await page.locator('.team-row.keyboard-active').getAttribute('data-row'),'0','up stays at the first team');
  assert.equal(JSON.stringify((await state()).rounds[0].entries),beforeMove,'up on a rate radio cannot change the rate');
  await page.keyboard.down('ArrowDown'); await settled();
  assert.equal(await page.locator('.team-row.keyboard-active').getAttribute('data-row'),'1','down moves to the next team');
  await page.keyboard.down('ArrowDown'); await settled();await page.keyboard.up('ArrowDown');
  assert.equal(JSON.stringify((await state()).rounds[0].entries),beforeMove,'moving and holding an arrow never changes answers');
  await key('ArrowDown');
  assert.equal(await page.locator('.team-row.keyboard-active').getAttribute('data-row'),'1','down stays at the last team');
  await key('ArrowUp');
  await key('ArrowDown'); await key('0'); assert.equal((await state()).rounds[0].entries[1].missing,true);
  await key('2'); assert.equal((await state()).rounds[0].entries[1].cause,null,'missing entries remain disabled');
  await key('0'); await key('2'); await key('6');
  await key('ArrowUp'); await page.locator('.team-row[data-row="0"] input[data-field="cause"][value="A"]').focus();
  await key('ArrowRight'); assert.equal((await state()).rounds[0].entries[0].cause,'B','native radio arrow navigation works');
  await key('1'); await key('5');
  await page.evaluate(()=>document.fonts.ready);
  await page.screenshot({path:path.join(out,'keyboard-entry.png')});
  await page.setViewportSize({width:390,height:844});
  await key('ArrowDown'); assert.equal(await page.locator('.team-row.mobile-active').getAttribute('data-row'),'1');
  await page.screenshot({path:path.join(out,'keyboard-entry-mobile.png'),fullPage:true});
  await key('ArrowUp'); await page.setViewportSize({width:1280,height:720});
  await key('n'); const originals=JSON.stringify((await state()).rounds[0].originals);
  await key('1'); assert.equal(JSON.stringify((await state()).rounds[0].originals),originals);
  for(let i=0;i<4;i++)await key('n');
  assert.equal(await phase(),'roundFeedback');
  await key('2'); assert.match(await page.locator('#team-detail h2').innerText(),/2모둠/);
  await key('n'); await key('r'); await key('4'); await key('6');
  const beforeCorrectionMove=JSON.stringify((await state()).rounds[0].corrections);
  await key('ArrowDown');
  assert.equal(await page.locator('.team-row.keyboard-active').getAttribute('data-row'),'1');
  assert.equal(JSON.stringify((await state()).rounds[0].corrections),beforeCorrectionMove,'correction arrow navigation does not change corrections');
  await key('ArrowUp');
  assert.equal(JSON.stringify((await state()).rounds[0].originals),originals,'keyboard corrections preserve scored originals');
  await key('r'); await key('4'); assert.equal(JSON.stringify((await state()).rounds[0].originals),originals);
  await key('l'); await key('e'); assert.equal(await phase(),'correction','retired keys do not open an optional screen');
  await key('n');
  for(let round=1;round<4;round++) {
    for(let i=0;i<3;i++)await key('n');
    assert.equal(await phase(),'responseEntry');
    await key('1');await key('5');await key('ArrowDown');await key('0');
    for(let i=0;i<7;i++)await key('n');
  }
  assert.equal(await phase(),'individualA');
  for(let i=0;i<3;i++)await key('n');
  assert.equal(await phase(),'final');
  await key('n'); assert.equal(await phase(),'final','final screen cannot restart or print by accident');
  const other=await page.context().newPage(); await other.goto(url);
  const newer=JSON.stringify(C.dispatch(await state(),{type:'timerAdd'}));
  await other.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:C.STORAGE_KEY,raw:newer});
  await page.waitForFunction(()=>document.querySelector('#app').dataset.phase==='conflict');
  await key('n');await key('p');await key('1');
  assert.equal(await page.evaluate(key=>localStorage.getItem(key),C.STORAGE_KEY),newer,'shortcuts cannot overwrite another tab after conflict');
  await page.locator('[data-action="reloadLatest"]').click();await other.close();
  await page.locator('#home').click(); await page.locator('[data-action="setup"]').click();
  const name=page.locator('input[name="name-0"]'); await name.fill(''); await name.focus(); await page.keyboard.type('npt123');
  assert.equal(await name.inputValue(),'npt123'); assert.equal(await phase(),'setup');
  assert.deepEqual(errors,[]);
  console.log('PASS keyboard: four rounds, answers and team navigation, timer, reveals, corrections, core flow, help/disable, native controls, IME and modal guards.');
  await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
